server:
    port: 8085
spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:file:C:/Users/ASUS/tacocloud
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    thymeleaf:
        cache: false
taco:
    discount:
        codes:
            abcdef: 10
    order:
        concac: 20
    orders:
        page-size: 10
